version: "3.9"
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000" # Web UI port
      - "9092:9092" # Scanner port
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      # เพิ่ม Environment Variables สำหรับเชื่อมต่อ PostgreSQL ภายนอก
      - SONAR_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/postgres  # หรือ jdbc:postgresql://<IP Address เครื่อง Host>:5432/postgres
      - SONAR_JDBC_USERNAME=postgres  # Username ของ PostgreSQL database ของคุณ
      - SONAR_JDBC_PASSWORD=postgres  # Password ของ PostgreSQL database ของคุณ
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_conf:
  sonarqube_extensions: